# Generated by Django 4.2.30 on 2026-06-09 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('religion', models.CharField(blank=True, max_length=50, null=True)),
                ('blood_type', models.CharField(blank=True, max_length=5, null=True)),
                ('political_leaning', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('shipping_address', models.TextField()),
            ],
        ),
    ]
