# Generated by Django 4.2.30 on 2026-06-09 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_email', models.EmailField(max_length=254)),
                ('action_details', models.TextField()),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'pdp_action_audit_logs',
            },
        ),
    ]
