# Generated by Django 4.2.30 on 2026-06-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('consent_given', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('policy_version', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'pdp_consent_logs',
            },
        ),
    ]
