# Generated by Django 4.2.30 on 2026-06-17 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac_audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessauditlog',
            name='hash_signature',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='accessauditlog',
            name='previous_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
