# Generated by Django 4.2.30 on 2026-06-09 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_cause', models.CharField(max_length=255)),
                ('impacted_subjects_count', models.IntegerField()),
                ('remediation_actions', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reported_to_bppa', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'pdp_incident_reports',
            },
        ),
    ]
