# Generated by Django 4.2.30 on 2026-06-17 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_portability', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataExportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('download_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pdp_data_export_jobs',
            },
        ),
    ]
