# Generated by Django 4.2.30 on 2026-06-06 17:12

from django.db import migrations, models
import koans.k03_data_security.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nik', koans.k03_data_security.models.EncryptedCharField(max_length=255)),
            ],
            options={
                'db_table': 'pdp_customer_records',
            },
        ),
    ]
